# This is a basic workflow to help you get started with Actions

name: Current-date_test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
    RUN_WIDNOWS: echo "ReleaseDate=$(Get-Date -Format "yyyy-MM-dd")"
    RUN_UBUNTU: echo "echo $(date +'%Y-%m-%d')"
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  my_ubuntu_job:
    name: test job
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: use env var in env var
        run: echo "$(date +'%Y-%m-%d')"
      - name: try use var
        run: ${{ env.RUN_UBUNTU }}
  # This workflow contains a single job called "build"
  my_win_job:
    name: test win_job
    # The type of runner that the job will run on
    runs-on: windows-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: get date
        run: ${{ env.RUN_WIDNOWS }}
        

