# This is a basic workflow to help you get started with Actions

name: Current-date_test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
    RUN: echo "$(date +'%Y-%m-%d')"
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  my_job:
    name: test job
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: use env var in env var
        run: ${{ env.RUN }}
        

