# This is a basic workflow to help you get started with Actions

name: Current-date_test_2

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  DATEZY: '%date:~10,4%-%date:~4,2%-%date:~7,2%'
  DATEZY_2: $(Get-Date -Format "yyyy-MM-dd")

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
#  ubuntu_job:
 #   name: ubuntu test job
    # The type of runner that the job will run on
  #  runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
   # steps:
    #  - name: set current date as env var
     #   run: echo "CURRENT_DATEU::$(date + '%Y-%m-%d')" >> $GITHUB_ENV
      #- name: use env var in env var
       # run: echo CurrentDate=${{ env.UBUNTU_CURRENT_DATE }}
        
  windows_job:
      name: windows test job
      # The type of runner that the job will run on
      runs-on: windows-latest
      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        - uses: actions/checkout@v2
        - name: Set Current Date Env Variable
          run: echo "CURRENT_DATE=$(Get-Date -Format "yyyy-MM-dd")" >> $GITHUB_ENV
        - name: global env cmd use
          run: echo date=${{env.DATEZY}}
        - name: global env use
          run: echo date=${{env.DATEZY_2}}
        - name: Set CMD Date Env Variable
          run: echo "CURRENT_DATE_CMD=%date:~10,4%-%date:~4,2%-%date:~7,2%" >> $GITHUB_ENV
        - name: Output new CMD var
          run: echo date=${{ env.CURRENT_DATE_CMD }}       
        - name: Output new var
          run: echo date=${{ env.CURRENT_DATE }}
        - name: use env var in run
          run: echo CurrentDate=$CURRENT_DATE
