# This is a basic workflow to help you get started with Actions

name: Current-date_test_2

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  CURRENT_DATE: "%date:~10,4%-%date:~4,2%-%date:~7,2%"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:       
  windows_job:
      name: windows test job
      # The type of runner that the job will run on
      runs-on: windows-latest
      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        - uses: actions/checkout@v2
        - name: Print Date
          run: .\example.bat ${{ env.CURRENT_DATE }}
